
package views;

import config.Dialogs;
import com.formdev.flatlaf.FlatLightLaf;
import config.Variables;
import database.*;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;

/**
 *
 * @author NUN
 */
public class AddDevice extends javax.swing.JFrame {

    /**
     * Creates new form AddDevice
     */
    public AddDevice() {
        initComponents();
        Image icon = Variables.icon;
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adddevicepanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        newDeviceCategory = new javax.swing.JComboBox<>();
        newDeviceName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        property1 = new javax.swing.JTextField();
        property2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        property6 = new javax.swing.JTextField();
        property7 = new javax.swing.JTextField();
        property8 = new javax.swing.JTextField();
        property9 = new javax.swing.JTextField();
        property3 = new javax.swing.JTextField();
        property4 = new javax.swing.JTextField();
        property5 = new javax.swing.JTextField();
        property10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        newDeviceAmount = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        newDeviceSerialNum6 = new javax.swing.JTextField();
        newDeviceSerialNum7 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        newDeviceSerialNum9 = new javax.swing.JTextField();
        newDeviceSerialNum8 = new javax.swing.JTextField();
        newDeviceSerialNum2 = new javax.swing.JTextField();
        newDeviceSerialNum1 = new javax.swing.JTextField();
        newDeviceSerialNum4 = new javax.swing.JTextField();
        newDeviceSerialNum3 = new javax.swing.JTextField();
        newDeviceSerialNum10 = new javax.swing.JTextField();
        newDeviceSerialNum5 = new javax.swing.JTextField();
        createDeviceButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        newDeviceWarrantyDateCheckBox = new javax.swing.JCheckBox();
        newDeviceWarrantyCheckBox = new javax.swing.JCheckBox();
        newDeviceWarrantyType = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        newDeviceWarrantyDate = new org.jdesktop.swingx.JXDatePicker();
        newDeviceWarranty = new javax.swing.JSpinner();

        setTitle("Cihaz Ekle");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        adddevicepanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                adddevicepanelComponentShown(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Kategori:");

        newDeviceCategory.setMaximumRowCount(20);
        newDeviceCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceCategoryActionPerformed(evt);
            }
        });

        newDeviceName.setToolTipText("Cihaz İsmi");
        newDeviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceNameActionPerformed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Cihaz İsmi:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(newDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newDeviceCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(newDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(newDeviceCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        property1.setToolTipText("");
        property1.setEnabled(false);
        property1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property1ActionPerformed(evt);
            }
        });

        property2.setToolTipText("");
        property2.setEnabled(false);
        property2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property2ActionPerformed(evt);
            }
        });

        jLabel19.setText("1.");

        jLabel20.setText("2.");

        jLabel21.setText("3.");

        jLabel22.setText("4.");

        jLabel23.setText("5.");

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Özellikler");

        jLabel33.setText("6.");

        jLabel34.setText("7.");

        jLabel35.setText("8.");

        jLabel36.setText("9.");

        jLabel37.setText("10.");

        property6.setToolTipText("Cihaz İsmi");
        property6.setEnabled(false);
        property6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property6ActionPerformed(evt);
            }
        });

        property7.setToolTipText("Cihaz İsmi");
        property7.setEnabled(false);
        property7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property7ActionPerformed(evt);
            }
        });

        property8.setToolTipText("");
        property8.setEnabled(false);
        property8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property8ActionPerformed(evt);
            }
        });

        property9.setToolTipText("");
        property9.setEnabled(false);
        property9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property9ActionPerformed(evt);
            }
        });

        property3.setToolTipText("");
        property3.setEnabled(false);
        property3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property3ActionPerformed(evt);
            }
        });

        property4.setToolTipText("");
        property4.setEnabled(false);
        property4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property4ActionPerformed(evt);
            }
        });

        property5.setToolTipText("");
        property5.setEnabled(false);
        property5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property5ActionPerformed(evt);
            }
        });

        property10.setToolTipText("");
        property10.setEnabled(false);
        property10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(property10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(property1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(property6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(property2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(property7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(property3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(property8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(property4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(property9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(property5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(property10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        newDeviceAmount.setName(""); // NOI18N
        newDeviceAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newDeviceAmountStateChanged(evt);
            }
        });

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Cihaz Adedi:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(newDeviceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(newDeviceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel44.setText("6.");

        jLabel45.setText("7.");

        jLabel46.setText("8.");

        jLabel47.setText("9.");

        jLabel48.setText("10.");

        newDeviceSerialNum6.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum6.setEnabled(false);
        newDeviceSerialNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum6ActionPerformed(evt);
            }
        });

        newDeviceSerialNum7.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum7.setEnabled(false);
        newDeviceSerialNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum7ActionPerformed(evt);
            }
        });

        jLabel49.setText("1.");

        jLabel50.setText("2.");

        jLabel51.setText("3.");

        jLabel52.setText("4.");

        jLabel53.setText("5.");

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Seri Numaraları");

        newDeviceSerialNum9.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum9.setEnabled(false);
        newDeviceSerialNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum9ActionPerformed(evt);
            }
        });

        newDeviceSerialNum8.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum8.setEnabled(false);
        newDeviceSerialNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum8ActionPerformed(evt);
            }
        });

        newDeviceSerialNum2.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum2.setEnabled(false);
        newDeviceSerialNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum2ActionPerformed(evt);
            }
        });

        newDeviceSerialNum1.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum1.setEnabled(false);
        newDeviceSerialNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum1ActionPerformed(evt);
            }
        });

        newDeviceSerialNum4.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum4.setEnabled(false);
        newDeviceSerialNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum4ActionPerformed(evt);
            }
        });

        newDeviceSerialNum3.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum3.setEnabled(false);
        newDeviceSerialNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum3ActionPerformed(evt);
            }
        });

        newDeviceSerialNum10.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum10.setEnabled(false);
        newDeviceSerialNum10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum10ActionPerformed(evt);
            }
        });

        newDeviceSerialNum5.setToolTipText("Cihaz İsmi");
        newDeviceSerialNum5.setEnabled(false);
        newDeviceSerialNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceSerialNum5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(newDeviceSerialNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(newDeviceSerialNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(newDeviceSerialNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(newDeviceSerialNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(newDeviceSerialNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(newDeviceSerialNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(newDeviceSerialNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(newDeviceSerialNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(newDeviceSerialNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(newDeviceSerialNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(newDeviceSerialNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(newDeviceSerialNum10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createDeviceButton.setText("Oluştur");
        createDeviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeviceButtonActionPerformed(evt);
            }
        });

        newDeviceWarrantyDateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceWarrantyDateCheckBoxActionPerformed(evt);
            }
        });

        newDeviceWarrantyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceWarrantyCheckBoxActionPerformed(evt);
            }
        });

        newDeviceWarrantyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gün", "Ay", "Yıl" }));
        newDeviceWarrantyType.setToolTipText("Garanti Tarih Türü");
        newDeviceWarrantyType.setEnabled(false);
        newDeviceWarrantyType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceWarrantyTypeActionPerformed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Garanti Bilgileri");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Tarih Türü:");

        newDeviceWarrantyDate.setEnabled(false);
        newDeviceWarrantyDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDeviceWarrantyDateActionPerformed(evt);
            }
        });

        newDeviceWarranty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newDeviceWarranty.setEnabled(false);
        newDeviceWarranty.setName(""); // NOI18N
        newDeviceWarranty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newDeviceWarrantyStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(newDeviceWarrantyType, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newDeviceWarrantyCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newDeviceWarrantyDateCheckBox))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newDeviceWarrantyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newDeviceWarranty))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newDeviceWarrantyDateCheckBox)
                    .addComponent(newDeviceWarrantyDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newDeviceWarrantyCheckBox)
                    .addComponent(newDeviceWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(newDeviceWarrantyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adddevicepanelLayout = new javax.swing.GroupLayout(adddevicepanel);
        adddevicepanel.setLayout(adddevicepanelLayout);
        adddevicepanelLayout.setHorizontalGroup(
            adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adddevicepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adddevicepanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adddevicepanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adddevicepanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(createDeviceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        adddevicepanelLayout.setVerticalGroup(
            adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adddevicepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adddevicepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adddevicepanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adddevicepanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adddevicepanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createDeviceButton)))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adddevicepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adddevicepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    DashboardDatabase sdb = new DashboardDatabase();
    
    private void newDeviceCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceCategoryActionPerformed
        if(newDeviceCategory.getSelectedItem()==null) return;
        String selected = newDeviceCategory.getSelectedItem().toString();
        List<String[]> values = sdb.getCategorybyName(selected);
        boolean p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;
        int b = Integer.valueOf(values.get(0)[2]);
        switch (b) {
            case 0:
            p1=false;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 1:
            p1=true;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 2:
            p1=true;
            p2=true;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 3:
            p1=true;
            p2=true;
            p3=true;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 4:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 5:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 6:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 7:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 8:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=false;
            p10=false;
            break;
            case 9:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=true;
            p10=false;
            break;
            case 10:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=true;
            p10=true;
            break;
            default:
            p1=false;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
        }
        property1.setEnabled(p1);property2.setEnabled(p2);property3.setEnabled(p3);property4.setEnabled(p4);property5.setEnabled(p5);
        property6.setEnabled(p6);property7.setEnabled(p7);property8.setEnabled(p8);property9.setEnabled(p9);property10.setEnabled(p10);
        if(values.size()<=1) return;
        property1.setToolTipText(values.get(1)[0]);property2.setToolTipText(values.get(1)[1]);property3.setToolTipText(values.get(1)[2]);property4.setToolTipText(values.get(1)[3]);
        property5.setToolTipText(values.get(1)[4]);property6.setToolTipText(values.get(1)[5]);property7.setToolTipText(values.get(1)[6]);property8.setToolTipText(values.get(1)[7]);
        property9.setToolTipText(values.get(1)[8]);property10.setToolTipText(values.get(1)[9]);
    }//GEN-LAST:event_newDeviceCategoryActionPerformed

    private void newDeviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceNameActionPerformed

    private void property1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property1ActionPerformed

    private void property2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property2ActionPerformed

    private void property6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property6ActionPerformed

    private void property7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property7ActionPerformed

    private void property8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property8ActionPerformed

    private void property9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property9ActionPerformed

    private void property3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property3ActionPerformed

    private void property4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property4ActionPerformed

    private void property5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property5ActionPerformed

    private void property10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property10ActionPerformed

    private void newDeviceAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newDeviceAmountStateChanged
        int a = (Integer) newDeviceAmount.getValue();
        boolean p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;
        switch (a) {
            case 0:
            p1=false;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 1:
            p1=true;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 2:
            p1=true;
            p2=true;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 3:
            p1=true;
            p2=true;
            p3=true;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 4:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 5:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 6:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 7:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=false;
            p9=false;
            p10=false;
            break;
            case 8:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=false;
            p10=false;
            break;
            case 9:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=true;
            p10=false;
            break;
            case 10:
            p1=true;
            p2=true;
            p3=true;
            p4=true;
            p5=true;
            p6=true;
            p7=true;
            p8=true;
            p9=true;
            p10=true;
            break;
            default:
            p1=false;
            p2=false;
            p3=false;
            p4=false;
            p5=false;
            p6=false;
            p7=false;
            p8=false;
            p9=false;
            p10=false;
            break;
        }
        newDeviceSerialNum1.setEnabled(p1);newDeviceSerialNum2.setEnabled(p2);newDeviceSerialNum3.setEnabled(p3);newDeviceSerialNum4.setEnabled(p4);newDeviceSerialNum5.setEnabled(p5);
        newDeviceSerialNum6.setEnabled(p6);newDeviceSerialNum7.setEnabled(p7);newDeviceSerialNum8.setEnabled(p8);newDeviceSerialNum9.setEnabled(p9);newDeviceSerialNum10.setEnabled(p10);
    }//GEN-LAST:event_newDeviceAmountStateChanged

    private void newDeviceSerialNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum6ActionPerformed

    private void newDeviceSerialNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum7ActionPerformed

    private void newDeviceSerialNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum9ActionPerformed

    private void newDeviceSerialNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum8ActionPerformed

    private void newDeviceSerialNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum2ActionPerformed

    private void newDeviceSerialNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum1ActionPerformed

    private void newDeviceSerialNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum4ActionPerformed

    private void newDeviceSerialNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum3ActionPerformed

    private void newDeviceSerialNum10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum10ActionPerformed

    private void newDeviceSerialNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceSerialNum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceSerialNum5ActionPerformed

    private void createDeviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeviceButtonActionPerformed
        if(newDeviceWarrantyDateCheckBox.isSelected() && newDeviceWarrantyDate.getDate() == null){
            Dialogs.infoBox("Garanti bitiş tarihini giriniz!", "Eksik Bilgi");
            return;
        }
        if(newDeviceName.getText() == null || newDeviceName.getText().equals("")){
            Dialogs.infoBox("Lütfen cihaz ismi giriniz!", "Eksik Bilgi");
            return;
        }
        if(newDeviceCategory.getSelectedItem() == null){
            Dialogs.infoBox("Lütfen bir kategori seçiniz!", "Eksik Bilgi");
            return;
        }
        String deviceName = newDeviceName.getText(), category = newDeviceCategory.getSelectedItem().toString(), 
        p1 = property1.getText(), p2 = property2.getText(), type = newDeviceWarrantyType.getSelectedItem().toString(),
        p3 = property3.getText(), p4 = property4.getText(), p5 = property5.getText(), p6 = property6.getText(), p7 = property7.getText(), p8 = property8.getText(),
        p9 = property9.getText(), p10 = property10.getText(),snum1=newDeviceSerialNum1.getText(),snum2=newDeviceSerialNum2.getText(),snum3=newDeviceSerialNum3.getText(),
        snum4=newDeviceSerialNum4.getText(),snum5=newDeviceSerialNum5.getText(),snum6=newDeviceSerialNum6.getText(),snum7=newDeviceSerialNum7.getText(),
        snum8=newDeviceSerialNum8.getText(),snum9=newDeviceSerialNum9.getText(),snum10=newDeviceSerialNum10.getText();
        int deviceNum = (Integer) newDeviceAmount.getValue(), warranty = (Integer) newDeviceWarranty.getValue();
        List<String> serialNums = new ArrayList<>(Arrays.asList(snum1, snum2, snum3, snum4, snum5, snum6, snum7, snum8, snum9, snum10));
        List<String> properties = new ArrayList<>(Arrays.asList(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10));
        if(deviceNum <= 0){
            Dialogs.infoBox("Cihaz adedi 1'den küçük olamaz!", "Eksik Bilgi");
            return;
        }
        int x = 0;
        for(String serialNum : serialNums){
            if(serialNum == null || serialNum.equals("")){
                x++;
            }
        }
        if(10-x<deviceNum){
            Dialogs.infoBox("Belirtilen sayıda seri numarası girilmedi!", "Eksik Bilgi");
            return;
        }
        Date date = newDeviceWarrantyDate.getDate();
        LocalDate warrantyDate = newDeviceWarrantyDate.getDate() == null ? null: date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        sdb.addDevices(deviceName, category, warrantyDate, warranty, type, properties, serialNums);
    }//GEN-LAST:event_createDeviceButtonActionPerformed

    private void newDeviceWarrantyDateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceWarrantyDateCheckBoxActionPerformed
        if(newDeviceWarrantyDateCheckBox.isSelected()){
            newDeviceWarrantyDate.setEnabled(true);
            newDeviceWarranty.setEnabled(false);
            newDeviceWarranty.setValue(0);
            newDeviceWarrantyType.setEnabled(false);
            newDeviceWarrantyType.setVisible(false);
            jLabel29.setVisible(false);
            if(newDeviceWarrantyCheckBox.isSelected())
            newDeviceWarrantyCheckBox.doClick();
        }else{
            newDeviceWarrantyDate.setEnabled(false);
        }
    }//GEN-LAST:event_newDeviceWarrantyDateCheckBoxActionPerformed

    private void newDeviceWarrantyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceWarrantyCheckBoxActionPerformed
        if(newDeviceWarrantyCheckBox.isSelected()){
            newDeviceWarranty.setEnabled(true);
            newDeviceWarrantyType.setEnabled(true);
            newDeviceWarrantyType.setVisible(true);
            jLabel29.setVisible(true);
            newDeviceWarrantyDate.setEnabled(false);
            if(newDeviceWarrantyDateCheckBox.isSelected())
            newDeviceWarrantyDateCheckBox.doClick();
        }else{
            newDeviceWarranty.setValue(0);
            newDeviceWarranty.setEnabled(false);
            newDeviceWarrantyType.setEnabled(false);
            newDeviceWarrantyType.setVisible(false);
        }
    }//GEN-LAST:event_newDeviceWarrantyCheckBoxActionPerformed

    private void newDeviceWarrantyTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceWarrantyTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceWarrantyTypeActionPerformed

    private void newDeviceWarrantyDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeviceWarrantyDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceWarrantyDateActionPerformed

    private void newDeviceWarrantyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newDeviceWarrantyStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_newDeviceWarrantyStateChanged

    private void adddevicepanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_adddevicepanelComponentShown

    }//GEN-LAST:event_adddevicepanelComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jLabel29.setVisible(false);
        newDeviceWarrantyType.setVisible(false);
        List<String[]> values = sdb.getCategoriesFull();
        newDeviceCategory.addItem(null);
        DefaultComboBoxModel category = (DefaultComboBoxModel) newDeviceCategory.getModel();
        for (String[] eachRow : values) {
            if(category.getIndexOf(eachRow[1]) == -1){
                category.addElement(eachRow[1]); //obje haline gelen tablomuza metod yardımıyla verileri while döngüsü içerisinde satır satır ekliyoruz.
            }
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDevice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try{
           UIManager.setLookAndFeel(new FlatLightLaf());
       }catch(Exception e){
           
       }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDevice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adddevicepanel;
    private javax.swing.JButton createDeviceButton;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner newDeviceAmount;
    private javax.swing.JComboBox<String> newDeviceCategory;
    private javax.swing.JTextField newDeviceName;
    private javax.swing.JTextField newDeviceSerialNum1;
    private javax.swing.JTextField newDeviceSerialNum10;
    private javax.swing.JTextField newDeviceSerialNum2;
    private javax.swing.JTextField newDeviceSerialNum3;
    private javax.swing.JTextField newDeviceSerialNum4;
    private javax.swing.JTextField newDeviceSerialNum5;
    private javax.swing.JTextField newDeviceSerialNum6;
    private javax.swing.JTextField newDeviceSerialNum7;
    private javax.swing.JTextField newDeviceSerialNum8;
    private javax.swing.JTextField newDeviceSerialNum9;
    private javax.swing.JSpinner newDeviceWarranty;
    private javax.swing.JCheckBox newDeviceWarrantyCheckBox;
    private org.jdesktop.swingx.JXDatePicker newDeviceWarrantyDate;
    private javax.swing.JCheckBox newDeviceWarrantyDateCheckBox;
    private javax.swing.JComboBox<String> newDeviceWarrantyType;
    private javax.swing.JTextField property1;
    private javax.swing.JTextField property10;
    private javax.swing.JTextField property2;
    private javax.swing.JTextField property3;
    private javax.swing.JTextField property4;
    private javax.swing.JTextField property5;
    private javax.swing.JTextField property6;
    private javax.swing.JTextField property7;
    private javax.swing.JTextField property8;
    private javax.swing.JTextField property9;
    // End of variables declaration//GEN-END:variables
}
