
package views;

import config.Dialogs;
import config.Mail;
import com.formdev.flatlaf.*;
import config.Variables;
import javax.swing.UIManager;
import database.*;
import java.awt.Image;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author NUN
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
        Image icon = Variables.icon;
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caccountpasswordshowhide = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        nickname = new javax.swing.JTextField();
        caccountadminpasswordshowhide = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        permission = new javax.swing.JComboBox<>();
        caccountrepassword = new javax.swing.JPasswordField();
        caccountmainadmin = new javax.swing.JPasswordField();
        caccountpassword = new javax.swing.JPasswordField();

        setTitle("Hesap Oluştur");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        caccountpasswordshowhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountpasswordshowhideActionPerformed(evt);
            }
        });

        jLabel4.setText("Yetki:");

        jLabel5.setText("Ana Admin Şifresi:");

        createButton.setText("Oluştur");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        nickname.setToolTipText("Kullanıcı Adı");
        nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameActionPerformed(evt);
            }
        });

        caccountadminpasswordshowhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountadminpasswordshowhideActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullanıcı Adı:");

        jLabel2.setText("Şifre:");

        jLabel3.setText("Şifre Tekrar:");

        permission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "İzleyici", "Ana Admin" }));
        permission.setToolTipText("Oluşturulacak hesabın yetkisini seçiniz.");
        permission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionActionPerformed(evt);
            }
        });

        caccountmainadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountmainadminActionPerformed(evt);
            }
        });

        caccountpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caccountpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caccountpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caccountrepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(permission, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caccountpasswordshowhide)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caccountmainadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caccountadminpasswordshowhide)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caccountmainadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(caccountadminpasswordshowhide)
                                .addComponent(jLabel5)))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caccountpasswordshowhide, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(caccountpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caccountrepassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    CreateAccountDatabase cad = new CreateAccountDatabase();
    Mail mail = new Mail();

    public void getConfirmation(String code, String email, String nname, String password, String perm, String adminpassword) {

        boolean check = cad.checkMainAdminPassword(adminpassword);
        if(!check) return;
        
        String result = (String) JOptionPane.showInputDialog(
                this,
                email + " mailinize gelen doğrulama kodunu giriniz.",
                "Doğrulama",
                JOptionPane.PLAIN_MESSAGE,
                null,
                null,
                ""
        );
        if (!result.equals(code)) {
            if (result == null) {
                return;
            }
            Dialogs.errorBox("Geçersiz kod!", "Hata!");
            getConfirmation(code, email, nname, password, perm, adminpassword);
        } else {
            cad.createAccount(nname, password, perm, adminpassword);
        }
    }
    private void nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameActionPerformed

    private void permissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permissionActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String nname = nickname.getText(), password = String.valueOf(caccountpassword.getPassword()), repassword = String.valueOf(caccountrepassword.getPassword()), perm = permission.getItemAt(permission.getSelectedIndex()), adminpassword = String.valueOf(caccountmainadmin.getPassword());

        if (nname == null || nname.equals("")) {
            Dialogs.infoBox("Lütfen bir isim giriniz!", "Hata");
            return;
        }
        
        if (password.length() < 8) {
            Dialogs.infoBox("Şifreniz 8 karakter ya da daha uzun olmalı!", "Kısa Şifre");
            return;
        }

        if (!password.equals(repassword)) {
            Dialogs.infoBox("Şifreler uyuşmuyor!", "Uyumsuz Şifre");
            return;
        }
        
        if (adminpassword.length() < 1) {
            Dialogs.infoBox("Lütfen Ana Admin şifresini giriniz!", "Hata");
            return;
        }
        
        if (perm.equals("Ana Admin")) {
            int a = JOptionPane.showOptionDialog(this, "Oluşturmakta olduğunuz hesaba Ana Admin yetkisi vermek istediğinize emin misiniz?", "Uyarı", 0, 0, null, new String[]{"Evet", "Hayır"}, "Hayır");
            if (a == 1) {
                return;
            }
        }
        boolean check = cad.checkAccount(nname, password);
        if (check == false) {
            return;
        }
        int number = new Random().nextInt(999999);
        String code = String.format("%06d", number);
        String email = cad.getAddress();
        if (email == null) {
            Dialogs.errorBox("Veritabanına kayıtlı bir mail bulunamadı, bu sebeple otomatik kayıt yapılamıyor.\nLütfen veritabanına el ile yeni bir mail adresi kaydediniz.", "Hata!");
            return;
        }
        String result = mail.sendEmail(email, "Hesap Oluşturma - Doğrulama Kodu", "Doğrulama kodunuz:\n" + code);
        if (result.equals("connection error")) {
            Dialogs.errorBox("Mail bağlantısında bir sorun oluştu! Lütfen internet bağlantınızı kontrol ediniz.", "Bağlantı Hatası");
            return;
        } else if (result.equals("error")) {
            Dialogs.errorBox("Mail gönderilirken bir sorun oluştu! Lütfen daha sonra tekrar deneyiniz.", "Hata");
            return;
        }
        getConfirmation(code, email, nname, password, perm, adminpassword);
    }//GEN-LAST:event_createButtonActionPerformed

    private void caccountpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountpasswordActionPerformed

    private void caccountmainadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountmainadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caccountmainadminActionPerformed

    private void caccountpasswordshowhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountpasswordshowhideActionPerformed
        // TODO add your handling code here:
        if (caccountpasswordshowhide.isSelected()) {
            caccountpassword.setEchoChar((char) 0);
            caccountrepassword.setEchoChar((char) 0);
        } else {
            caccountpassword.setEchoChar('\u2022');
            caccountrepassword.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_caccountpasswordshowhideActionPerformed

    private void caccountadminpasswordshowhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caccountadminpasswordshowhideActionPerformed
        // TODO add your handling code here:
        if (caccountadminpasswordshowhide.isSelected()) {
            caccountmainadmin.setEchoChar((char) 0);
        } else {
            caccountmainadmin.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_caccountadminpasswordshowhideActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        nickname.setText(null);
        caccountpassword.setText(null);
        caccountrepassword.setText(null);
        caccountmainadmin.setText(null);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {

        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton caccountadminpasswordshowhide;
    private javax.swing.JPasswordField caccountmainadmin;
    private javax.swing.JPasswordField caccountpassword;
    private javax.swing.JRadioButton caccountpasswordshowhide;
    private javax.swing.JPasswordField caccountrepassword;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nickname;
    private javax.swing.JComboBox<String> permission;
    // End of variables declaration//GEN-END:variables
}
