
package views;
import config.Dialogs;
import com.formdev.flatlaf.*;
import javax.swing.*;
import database.*;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import config.Pair;
import config.Variables;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author NUN
 */
public class DeviceProperties extends javax.swing.JFrame {
    
    String ID;
    String currentName = "";
    String currentWarrantyDate = "";
    String currentCategory = "";
    String assignedProfileId;
    /**
     * Creates new form DeviceProperties
     * @param ID
     */
    public DeviceProperties(String ID) {
        this.ID = ID;
        initComponents();
        Image icon = Variables.icon;
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        assignedProfileID = new javax.swing.JLabel();
        assignedProfileName = new javax.swing.JLabel();
        showAssignedProfile = new javax.swing.JButton();
        removeAssignmentButton = new javax.swing.JButton();
        statusUpdateButton = new javax.swing.JButton();
        chooseStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        chooseProfile = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        assignButton = new javax.swing.JButton();
        showDeviceLog = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertiesTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        remainingWarranty = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        deviceName = new javax.swing.JTextField();
        status = new javax.swing.JLabel();
        deviceID = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        warrantyDate = new org.jdesktop.swingx.JXDatePicker();
        deviceCategoryComboBox = new javax.swing.JComboBox<>();
        serialNum = new javax.swing.JTextField();

        setTitle("Cihaz Özellikleri");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cihaz:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cihaz ID:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Seri Numarası:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Kategori:");

        jLabel9.setText("Durum:");

        jLabel10.setText("Profil ID:");

        jLabel11.setText("Profil İsmi:");

        showAssignedProfile.setText("Profili Görüntüle");
        showAssignedProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAssignedProfileActionPerformed(evt);
            }
        });

        removeAssignmentButton.setText("Atamayı Kaldır");
        removeAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAssignmentButtonActionPerformed(evt);
            }
        });

        statusUpdateButton.setText("Güncelle");
        statusUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusUpdateButtonActionPerformed(evt);
            }
        });

        chooseStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boşta", "Kullanımda", "Kullanım Dışı", "Tamirde" }));

        jLabel15.setText("Durum Seç:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Profil Seç:");

        assignButton.setText("Profile Ata");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        showDeviceLog.setText("Geçmişi Görüntüle");
        showDeviceLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDeviceLogActionPerformed(evt);
            }
        });

        updateButton.setText("Güncelle");
        updateButton.setEnabled(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Cihazı Sil");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        propertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", "Teknik Özellikler"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(propertiesTable);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Garanti Bitiş Tarihi:");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        remainingWarranty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        remainingWarranty.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Kalan Garanti Süresi:");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        deviceName.setEnabled(false);
        deviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceNameActionPerformed(evt);
            }
        });

        editButton.setText("Düzenle");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        warrantyDate.setEnabled(false);
        warrantyDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyDateActionPerformed(evt);
            }
        });

        deviceCategoryComboBox.setEnabled(false);

        serialNum.setEditable(false);
        serialNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(deviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assignedProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(assignedProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deviceID, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deviceCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(serialNum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(chooseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(statusUpdateButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chooseProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(assignButton))
                                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showDeviceLog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(editButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(updateButton))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(showAssignedProfile)
                                            .addComponent(removeAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warrantyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remainingWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(assignedProfileID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assignedProfileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showAssignedProfile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(serialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deviceID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(deviceCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(removeAssignmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chooseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(statusUpdateButton))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chooseProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addComponent(assignButton))
                        .addGap(59, 59, 59)
                        .addComponent(showDeviceLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateButton)
                            .addComponent(editButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remainingWarranty, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel20)
                        .addComponent(warrantyDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    DevicePropertiesDatabase dp = new DevicePropertiesDatabase();
    DashboardDatabase sdb = new DashboardDatabase();
    
    private void showAssignedProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAssignedProfileActionPerformed
        if(assignedProfileID.getText()==null||assignedProfileID.getText().equals("")) return;
        boolean check = dp.checkProfile(assignedProfileId);
        if(!check) return;
        ProfileProperties pp = new ProfileProperties(assignedProfileId);
        pp.setVisible(true);
    }//GEN-LAST:event_showAssignedProfileActionPerformed

    private void removeAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAssignmentButtonActionPerformed
        String deviceId = deviceID.getText(), devicename = deviceName.getText(), profileID = assignedProfileID.getText();
        if(profileID==null||profileID.equals("")) return;
        dp.removeAssignment(deviceId, devicename, profileID);
        assignedProfileID.setText("");
        assignedProfileName.setText("");
        if(status.getText().equals("Kullanımda"))
            status.setText("Boşta");
        chooseProfile.setEnabled(true);
        assignButton.setEnabled(true);
    }//GEN-LAST:event_removeAssignmentButtonActionPerformed

    private void statusUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusUpdateButtonActionPerformed
        String devicestatus = chooseStatus.getSelectedItem().toString(), ID = deviceID.getText(), id = assignedProfileID.getText();
        if((devicestatus.equals("Boşta") || devicestatus.equals("Kullanım Dışı") || devicestatus.equals("Tamirde")) && status.getText().equals("Kullanımda") && id!=null&&!id.equals("")){
            Dialogs.errorBox("Durumu değiştirmek için lütfen atamayı kaldırınız!", "Hata");
            return;
        }
        dp.updateStatus(ID, devicestatus);
        status.setText(devicestatus);
    }//GEN-LAST:event_statusUpdateButtonActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        String profileName = chooseProfile.getSelectedItem().toString(), deviceId = deviceID.getText(), devicename = deviceName.getText(), devicestatus = status.getText(), id = assignedProfileID.getText();
        if(!devicestatus.equals("Boşta") && (devicestatus.equals("Kullanımda") && (id!=null && !id.equals("")))){
            Dialogs.errorBox("Cihaz zaten bir profile atanmış durumda ya da atamaya uygun değil!", "Hata");
            return;
        }else if(devicestatus.equals("Kullanım Dışı") || devicestatus.equals("Tamirde")){
            Dialogs.errorBox("Cihaz atamaya uygun değil!", "Hata");
            return;
        }
        String profileID = dp.assign(profileName, deviceId, devicename);
        assignedProfileID.setText(profileID);
        assignedProfileName.setText(profileName);
        assignedProfileId = profileID;
        status.setText("Kullanımda");
    }//GEN-LAST:event_assignButtonActionPerformed

    private void showDeviceLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDeviceLogActionPerformed
        HistoryOfDevice log = new HistoryOfDevice(ID);
        log.setVisible(true);
    }//GEN-LAST:event_showDeviceLogActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String newName = deviceName.getText(), newWarrantyDate = warrantyDate.getDate().toString(), newCategory = deviceCategoryComboBox.getSelectedItem().toString(), deviceId = deviceID.getText();
        if(newName.equals(currentName) && newWarrantyDate.equals(currentWarrantyDate) && newCategory.equals(currentCategory)){
            editButton.setEnabled(true); updateButton.setEnabled(false);
            deviceName.setEnabled(false); warrantyDate.setEnabled(false);
            deviceCategoryComboBox.setEnabled(false);
            return;
        }
        Date date = warrantyDate.getDate();
        LocalDate localdate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        dp.edit(deviceId, newName, localdate, newCategory);
        editButton.setEnabled(true); updateButton.setEnabled(false);
        deviceName.setEnabled(false); warrantyDate.setEnabled(false);
        deviceCategoryComboBox.setEnabled(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int n = Dialogs.questionBox(this, "Bu cihazı silmek istediğinize emin misiniz?", "Uyarı");
        if(n!=0) return;
        String devicename = deviceName.getText();
        dp.deleteDevice(ID, devicename, assignedProfileId);
        removeAssignmentButton.setEnabled(false); chooseStatus.setEnabled(false); statusUpdateButton.setEnabled(false); chooseProfile.setEnabled(false);
        assignButton.setEnabled(false); showDeviceLog.setEnabled(false); editButton.setEnabled(false); updateButton.setEnabled(false);
        deleteButton.setEnabled(false); deviceName.setEnabled(false); warrantyDate.setEnabled(false); deviceCategoryComboBox.setEnabled(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceNameActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        currentName = deviceName.getText(); currentWarrantyDate = warrantyDate.getDate().toString(); currentCategory = deviceCategoryComboBox.getSelectedItem().toString();
        editButton.setEnabled(false); updateButton.setEnabled(true);
        deviceName.setEnabled(true); warrantyDate.setEnabled(true); deviceCategoryComboBox.setEnabled(true);
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        serialNum.setBackground(null);
        serialNum.setBorder(null);
        Pair<Date, String[]> p = dp.getDevice(ID);
        Date devicewarranty = p.getKey();
        String[] details = p.getValue();

        String categoryname = details[0], devicename = details[1], devicestatus = details[2], deviceAssignedProfile = details[3], deviceAssignedProfileID = details[4], 
                deviceRemainingWarranty = details[5], serialnum = details[6];
        
        List<String[]> properties = dp.getDeviceProperties(devicename, categoryname);
        DefaultTableModel model=(DefaultTableModel) propertiesTable.getModel(); //tablo nesnemizi obje haline getiriyoruz.
        model.setRowCount(0); //veri listelenmeden önce başlangıç satırının sıfır yapıyor.
        for (String[] eachRow : properties) {
            model.addRow(eachRow); //obje haline gelen tablomuza metod yardımıyla verileri while döngüsü içerisinde satır satır ekliyoruz.
        }
        
        List<String[]> values = sdb.getCategoriesFull();
        DefaultComboBoxModel category = (DefaultComboBoxModel) deviceCategoryComboBox.getModel();
        for (String[] eachRow : values) {
            if(category.getIndexOf(eachRow[1]) == -1){
                category.addElement(eachRow[1]); //obje haline gelen comboboxa metod yardımıyla verileri while döngüsü içerisinde satır satır ekliyoruz.
            }
        }
        
        List<String[]> profiles = dp.getProfilesFull();
        DefaultComboBoxModel profile = (DefaultComboBoxModel) chooseProfile.getModel();
        for (String[] eachRow : profiles) {
            if(profile.getIndexOf(eachRow[1]) == -1){
                profile.addElement(eachRow[1]); //obje haline gelen comboboxa metod yardımıyla verileri while döngüsü içerisinde satır satır ekliyoruz.
            }
        }

        category.setSelectedItem(categoryname);
        deviceName.setText(devicename);
        deviceID.setText(ID);
        serialNum.setText(serialnum);
        status.setText(devicestatus);
        assignedProfileID.setText(deviceAssignedProfileID);
        assignedProfileName.setText(deviceAssignedProfile);
        warrantyDate.setDate(devicewarranty);
        remainingWarranty.setText(deviceRemainingWarranty);
        assignedProfileId = deviceAssignedProfileID;
    }//GEN-LAST:event_formComponentShown

    private void warrantyDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warrantyDateActionPerformed

    private void serialNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
           UIManager.setLookAndFeel(new FlatLightLaf());
       }catch(Exception e){
           
       }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceProperties(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JLabel assignedProfileID;
    private javax.swing.JLabel assignedProfileName;
    private javax.swing.JComboBox<String> chooseProfile;
    private javax.swing.JComboBox<String> chooseStatus;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> deviceCategoryComboBox;
    private javax.swing.JLabel deviceID;
    private javax.swing.JTextField deviceName;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable propertiesTable;
    private javax.swing.JLabel remainingWarranty;
    private javax.swing.JButton removeAssignmentButton;
    private javax.swing.JTextField serialNum;
    private javax.swing.JButton showAssignedProfile;
    private javax.swing.JButton showDeviceLog;
    private javax.swing.JLabel status;
    private javax.swing.JButton statusUpdateButton;
    private javax.swing.JButton updateButton;
    private org.jdesktop.swingx.JXDatePicker warrantyDate;
    // End of variables declaration//GEN-END:variables
}
